"""Add requested_by_id to CleanupReport

Revision ID: 11945473c982
Revises: a33ebc3b71a9
Create Date: 2025-09-30 19:54:33.546432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11945473c982'
down_revision = 'a33ebc3b71a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleanup_report', schema=None) as batch_op:
        batch_op.alter_column('reported_by',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('photo',
               existing_type=sa.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.alter_column('photo_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('submitted_photo',
               existing_type=sa.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.alter_column('submitted_photo_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_cleanup_report_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cleanup_report_is_complete'), ['is_complete'], unique=False)
        batch_op.create_index(batch_op.f('ix_cleanup_report_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_cleanup_report_reported_by'), ['reported_by'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_cleanup_report_assigned_to_id'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cleanup_report_submitted_by_cleaner_id'), 'user', ['submitted_by_cleaner_id'], ['id'])
        batch_op.drop_column('rating')
        batch_op.drop_column('before_photo_filename')
        batch_op.drop_column('after_photo_filename')
        batch_op.drop_column('assigned_to_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_points'), ['points'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.drop_column('avg_rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_rating', sa.FLOAT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_points'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    with op.batch_alter_table('cleanup_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('after_photo_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('before_photo_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_cleanup_report_submitted_by_cleaner_id'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cleanup_report_assigned_to_id'), 'user', ['assigned_to_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_cleanup_report_reported_by'))
        batch_op.drop_index(batch_op.f('ix_cleanup_report_location'))
        batch_op.drop_index(batch_op.f('ix_cleanup_report_is_complete'))
        batch_op.drop_index(batch_op.f('ix_cleanup_report_created_at'))
        batch_op.alter_column('submitted_photo_filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('submitted_photo',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('photo_filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('photo',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('reported_by',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
