"""Initial migration

Revision ID: 1e5eab7d28ed
Revises: 96215ca963e6
Create Date: 2025-08-20 00:09:49.742135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5eab7d28ed'
down_revision = '96215ca963e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleanup_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('points_awarded', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitted_by_cleaner_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cleanup_report_is_complete'), ['is_complete'], unique=False)
        # Give the foreign key a name
        batch_op.create_foreign_key(
            'fk_cleanup_report_submitted_by_cleaner_id_user',  # <-- name
            'user', 
            ['submitted_by_cleaner_id'], 
            ['id']
        )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_points'), ['points'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_points'))
        batch_op.drop_column('points')

    with op.batch_alter_table('cleanup_report', schema=None) as batch_op:
        # Drop the foreign key by its name
        batch_op.drop_constraint('fk_cleanup_report_submitted_by_cleaner_id_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cleanup_report_is_complete'))
        batch_op.drop_column('submitted_by_cleaner_id')
        batch_op.drop_column('points_awarded')
        batch_op.drop_column('is_complete')

    # ### end Alembic commands ###
