"""add photo columns

Revision ID: a33ebc3b71a9
Revises: f183e4ea24a9
Create Date: 2025-09-30 10:30:40.066441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33ebc3b71a9'
down_revision = 'f183e4ea24a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleanup_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('before_photo_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('after_photo_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('requested_by_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_cleanup_report_created_at'))
        batch_op.drop_index(batch_op.f('ix_cleanup_report_is_complete'))
        batch_op.drop_index(batch_op.f('ix_cleanup_report_location'))
        batch_op.drop_index(batch_op.f('ix_cleanup_report_reported_by'))
        # batch_op.drop_constraint(None, type_='foreignkey')  # Skip dropping unnamed constraint
        batch_op.create_foreign_key('fk_cleanup_report_assigned_to_id', 'user', ['assigned_to_id'], ['id'])
        batch_op.create_foreign_key('fk_cleanup_report_requested_by_id', 'user', ['requested_by_id'], ['id'])
        batch_op.drop_column('photo')
        batch_op.drop_column('photo_filename')
        batch_op.drop_column('is_complete')
        batch_op.drop_column('submitted_photo')
        batch_op.drop_column('submitted_photo_filename')
        batch_op.drop_column('submitted_by_cleaner_id')
        batch_op.drop_column('reported_by')
        batch_op.drop_column('points_awarded')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_points'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_points'), ['points'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=1)

    with op.batch_alter_table('cleanup_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_awarded', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('reported_by', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('submitted_by_cleaner_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('submitted_photo_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('submitted_photo', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('is_complete', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('photo_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.BLOB(), nullable=True))
        batch_op.drop_constraint('fk_cleanup_report_assigned_to_id', type_='foreignkey')
        batch_op.drop_constraint('fk_cleanup_report_requested_by_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_cleanup_report_submitted_by_cleaner_id', 'user', ['submitted_by_cleaner_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_cleanup_report_reported_by'), ['reported_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_cleanup_report_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_cleanup_report_is_complete'), ['is_complete'], unique=False)
        batch_op.create_index(batch_op.f('ix_cleanup_report_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('assigned_to_id')
        batch_op.drop_column('requested_by_id')
        batch_op.drop_column('after_photo_filename')
        batch_op.drop_column('before_photo_filename')

    # ### end Alembic commands ###
