"""Add claimed_by fields to CleanupRequest

Revision ID: a5eaf5fd0a4f
Revises: 11945473c982
Create Date: 2025-11-11 23:37:46.952143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5eaf5fd0a4f'
down_revision = '11945473c982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_cleanup_request')
    with op.batch_alter_table('cleanup_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimed_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_cleanup_request_claimed_by_id', 'user', ['claimed_by_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_points'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_points'), ['points'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=1)

    with op.batch_alter_table('cleanup_request', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cleanup_request_claimed_by_id', type_='foreignkey')
        batch_op.drop_column('claimed_by_id')

    op.create_table('_alembic_tmp_cleanup_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('photo_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('requested_by_id', sa.INTEGER(), nullable=True),
    sa.Column('claimed_by_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by_id'], ['user.id'], name=op.f('fk_cleanup_request_claimed_by_id')),
    sa.ForeignKeyConstraint(['requested_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
